### ISSUE TITLE
Support multiple files on one run

### ISSUE THREAD

**Issue by nbernardes** [prewk/s3-cp-action#1]
When downloading multiple files from S3 we have to declare the step for each file. The action could support a list of files and avoid multiple steps.

**Comment by prewk** [comment]
Sorry for being late to answer: yeah that sounds reasonable! Truth be told, I just forked someone's action and made minor changes to fit my use case (needed copy..) so I'm barely familiar with the code. Although, the surface area is small so can't be that hard, but I don't think I really have the time to fix the feature.

Would you be willing to take a look at it yourself as a pull request? Your attempt is probably as good as mine. :)

**Comment by theovincent** [comment]
Hi @nunobernardes99,

You can use the flag --recursive and play with --exclude and --include for that. To add those flag to the command line, it is possible to use the variable [$ENDPOINT_APPEND](https://github.com/prewk/s3-cp-action/blob/667b4425eb185e4eab10459ba4d57e0c68b35b8a/entrypoint.sh#L40) or event better, simply put a variable with a descriptive name and it will be added at the end of the command line by [$*](https://github.com/prewk/s3-cp-action/blob/667b4425eb185e4eab10459ba4d57e0c68b35b8a/entrypoint.sh#L40). 

My yaml file looks like that:
```{bash}
- name: Download a several files from AWS
  uses: prewk/s3-cp-action@master
  env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    SOURCE: 's3://bucket_name/path_to_the_"folder"_in_AWS'
    DEST: 'path_to_the_folder_in_the_container'
    ENDPOINT_APPEND: --recursive
```
@prewk let me know if you want me to update the documentation to explain that this feature is available.

**Comment by prewk** [comment]
I would happily merge it!

**Comment by theovincent** [comment]
@prewk The pull request is opened. I will be apply to answer your comments if you have some 😃

**Comment by prewk** [comment]
Merged!
